version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python server.py
    env_file:
      - .env
    ports:
      - '5000:5000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: 'flaskproduct'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: